version: "3"
services:

  transactions-db:
    image: postgres:12
    container_name: transactions-db
    restart: always
    networks:
      - transactions-network
    environment:
      - POSTGRES_DB=transactions-db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456
    ports:
      - 5432:5432

  transactions-api:
    build: './'
    container_name: transactions-api
    depends_on:
      - transactions-db
    networks:
      - transactions-network
    environment:
      - PORT=8080
      - DB_HOST=transactions-db
      - DB_NAME=transactions-db
      - DB_USER=admin
      - DB_PASSWORD=123456
      - DB_PORT=5432
    ports:
      - 8080:8080

networks:
  transactions-network:
    driver: bridge