
server:
  port: ${PORT:8080}

spring:

  application:
    name: transactions-api

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:transactions-db}
    username: ${DB_USER:admin}
    password: ${DB_PASSWORD:123456}
    initialize: true

  # JPA CONFIG
  jpa:
    database: postgresql
    generate-ddl: false
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        session:
          events:
            log:
              LOG_QUERIES_SLOWER_THAN_MS: 30

  # FLYWAY CONFIG
  flyway:
    schemas: transactions

metadata:
  name: Transactions API
  description: Technical test case for pismo
  version: 1.0.0