
server:
  port: ${PORT:8080}

spring:

  application:
    name: transactions-api

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: password

  jpa:
    generate-ddl: false
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

  flyway:
    schemas: transactions

metadata:
  name: Transactions API
  description: Technical test case for pismo
  version: 1.0.0